# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Integration checks for generated AIPerf config schema maintenance."""

import copy
import json
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
import yaml
from jsonschema import Draft202012Validator
from pydantic import ValidationError
from pytest import param

from aiperf.config import AIPerfConfig, load_config_from_string
from tools.generate_config_schema import ConfigSchemaGenerator

REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATOR_PATH = REPO_ROOT / "tools" / "generate_config_schema.py"
SCHEMA_PATH = (
    REPO_ROOT / "src" / "aiperf" / "config" / "schema" / "aiperf-config.schema.json"
)


def _generated_schema() -> dict[str, Any]:
    result = ConfigSchemaGenerator().generate()
    return json.loads(result.files[0].content)


def _schema_error_messages(schema: dict[str, Any], config: dict[str, Any]) -> list[str]:
    validator = Draft202012Validator(schema)
    return [error.message for error in validator.iter_errors(config)]


def _minimal_benchmark_config(**benchmark_overrides: Any) -> dict[str, Any]:
    benchmark: dict[str, Any] = {
        "models": "llama-test",
        "endpoint": {"urls": ["http://localhost:8000/v1/chat/completions"]},
        "datasets": [
            {
                "name": "main",
                "type": "synthetic",
                "entries": 1,
                "prompts": {"isl": {"value": 512}, "osl": {"value": 128}},
            }
        ],
        "phases": [
            {
                "name": "profiling",
                "type": "concurrency",
                "requests": 1,
                "concurrency": 1,
            }
        ],
    }
    benchmark.update(benchmark_overrides)
    return {"benchmark": benchmark}


def _assert_schema_accepts(schema: dict[str, Any], config: dict[str, Any]) -> None:
    assert _schema_error_messages(schema, config) == []


def _iter_discriminators(obj: Any) -> Iterator[dict[str, Any]]:
    if isinstance(obj, dict):
        discriminator = obj.get("discriminator")
        if isinstance(discriminator, dict):
            yield discriminator
        for value in obj.values():
            yield from _iter_discriminators(value)
    elif isinstance(obj, list):
        for item in obj:
            yield from _iter_discriminators(item)


def test_generated_schema_phase_discriminators_use_phase_type() -> None:
    schema = _generated_schema()
    discriminators = list(_iter_discriminators(schema))

    assert all(
        discriminator.get("propertyName") != "adaptiveScaleStrategyType"
        for discriminator in discriminators
    )
    phase_discriminators = [
        discriminator
        for discriminator in discriminators
        if discriminator.get("mapping", {}).get("concurrency")
        == "#/$defs/ConcurrencyPhase"
    ]
    assert phase_discriminators
    for discriminator in phase_discriminators:
        assert discriminator["propertyName"] == "type"
        assert discriminator["mapping"] == {
            "concurrency": "#/$defs/ConcurrencyPhase",
            "poisson": "#/$defs/PoissonPhase",
            "gamma": "#/$defs/GammaPhase",
            "constant": "#/$defs/ConstantPhase",
            "user_centric": "#/$defs/UserCentricPhase",
            "fixed_schedule": "#/$defs/FixedSchedulePhase",
        }


def test_config_schema_generator_is_integrated_with_dev_workflow() -> None:
    assert GENERATOR_PATH.exists(), (
        "tools/generate_config_schema.py must generate the config schema"
    )
    generator_source = GENERATOR_PATH.read_text(encoding="utf-8")
    assert 'CONFIG_DIR = Path("src/aiperf/config")' in generator_source
    assert 'SCHEMA_FILE = SCHEMA_DIR / "aiperf-config.schema.json"' in generator_source
    assert "config_v2" not in generator_source

    makefile_source = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    assert "generate-config-schema" in makefile_source
    assert "check-config-schema" in makefile_source
    assert "python -m tools.generate_config_schema --check" in makefile_source

    pre_commit_source = (REPO_ROOT / ".pre-commit-config.yaml").read_text(
        encoding="utf-8"
    )
    assert "id: generate-config-schema" in pre_commit_source
    assert (
        "^src/aiperf/config/.*\\.py$|^tools/generate_config_schema\\.py$"
        in pre_commit_source
    )

    schema_source = SCHEMA_PATH.read_text(encoding="utf-8")
    assert "Auto-generated by tools/generate_config_schema.py" in schema_source


def test_generated_schema_accepts_runtime_scalar_prompt_distributions() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        datasets=[
            {
                "name": "main",
                "type": "synthetic",
                "entries": 1,
                "prompts": {"isl": 512, "osl": 128},
            }
        ]
    )

    parsed = AIPerfConfig.model_validate(copy.deepcopy(config))

    assert parsed.benchmark.datasets[0].prompts is not None
    assert parsed.benchmark.datasets[0].prompts.isl.expected_value == 512
    assert parsed.benchmark.datasets[0].prompts.osl.expected_value == 128
    _assert_schema_accepts(schema, config)


def test_generated_schema_rejects_benchmark_missing_dataset_like_runtime() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config()
    del config["benchmark"]["datasets"]

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


def test_generated_schema_rejects_noise_image_sampling_like_runtime() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        datasets=[
            {
                "name": "main",
                "type": "synthetic",
                "entries": 1,
                "prompts": {"isl": 512, "osl": 128},
                "images": {"sourceSampling": "shuffle-cycle"},
            }
        ]
    )

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


def test_generated_schema_accepts_finite_image_source_sampling_like_runtime() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        datasets=[
            {
                "name": "main",
                "type": "synthetic",
                "entries": 1,
                "prompts": {"isl": 512, "osl": 128},
                "images": {
                    "source": "assets",
                    "sourceSampling": "shuffle-cycle",
                },
            }
        ]
    )

    AIPerfConfig.model_validate(copy.deepcopy(config))
    _assert_schema_accepts(schema, config)


def test_generated_schema_accepts_runtime_single_dict_phases_shorthand() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases={"type": "concurrency", "requests": 1, "concurrency": 1}
    )

    parsed = AIPerfConfig.model_validate(copy.deepcopy(config))

    assert len(parsed.benchmark.phases) == 1
    assert parsed.benchmark.phases[0].name == "profiling"
    _assert_schema_accepts(schema, config)


def test_generated_schema_rejects_rate_phase_without_rate_source() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[{"name": "profiling", "type": "poisson", "requests": 1}]
    )

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


def test_generated_schema_rejects_rate_phase_with_both_rate_sources() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "poisson",
                "requests": 1,
                "rate": 100,
                "rateSeries": {
                    "points": [
                        {"timeS": 0, "qps": 5},
                        {"timeS": 10, "qps": 15},
                    ]
                },
            }
        ]
    )

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


@pytest.mark.parametrize("rate_series", [{}, {"points": []}])
def test_generated_schema_rejects_empty_rate_series(rate_series: dict) -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "poisson",
                "requests": 1,
                "rateSeries": rate_series,
            }
        ]
    )

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


def test_generated_schema_rejects_user_centric_rate_series() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "user_centric",
                "requests": 2,
                "rate": 10,
                "users": 2,
                "rateSeries": {
                    "points": [
                        {"timeS": 0, "qps": 5},
                        {"timeS": 10, "qps": 15},
                    ]
                },
            }
        ]
    )

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))

    assert _schema_error_messages(schema, config) != []


@pytest.mark.parametrize(
    "config",
    [
        param(
            _minimal_benchmark_config(
                dataset={
                    "type": "synthetic",
                    "entries": 1,
                    "prompts": {"isl": 512, "osl": 128},
                },
                datasets=None,
            ),
            id="singular-dataset-injects-name",
        ),
        param(
            _minimal_benchmark_config(
                datasets=[
                    {
                        "name": "main",
                        "type": "synthetic",
                        "entries": 1,
                        "isl": 512,
                        "osl": 128,
                    }
                ]
            ),
            id="synthetic-dataset-top-level-isl-osl",
        ),
        param(
            _minimal_benchmark_config(
                phases=None,
                warmup={"type": "concurrency", "requests": 1, "concurrency": 1},
                profiling={"type": "concurrency", "requests": 1, "concurrency": 1},
            ),
            id="warmup-profiling-shorthand",
        ),
        param(
            _minimal_benchmark_config(
                datasets=[
                    {
                        "name": "main",
                        "type": "synthetic",
                        "entries": 1,
                        "prompts": {
                            "isl": {"type": "fixed", "value": 512},
                            "osl": {"type": "normal", "mean": 128, "stddev": 0},
                        },
                    }
                ]
            ),
            id="explicit-distribution-type-keys",
        ),
        param(
            _minimal_benchmark_config(
                datasets=[
                    {
                        "name": "main",
                        "type": "synthetic",
                        "entries": 1,
                        "prompts": {
                            "isl": {
                                "peaks": [
                                    {"mean": 128, "stddev": 10, "weight": 60},
                                    {"mean": 512, "stddev": 20, "weight": 40},
                                ]
                            },
                            "osl": 128,
                        },
                    }
                ]
            ),
            id="multimodal-inline-peak-distributions",
        ),
        param(
            _minimal_benchmark_config(
                mlflow={
                    "trackingUri": "http://mlflow:5000",
                    "tags": "team:perf,env:test",
                }
            ),
            id="mlflow-tags-string",
        ),
        param(
            _minimal_benchmark_config(
                accuracy={"benchmark": "mmlu", "tasks": "abstract_algebra,anatomy"}
            ),
            id="accuracy-tasks-string",
        ),
        param(
            _minimal_benchmark_config(
                datasets=[
                    {
                        "name": "main",
                        "type": "synthetic",
                        "entries": 1,
                        "prompts": {"isl": 512, "osl": 128},
                        "video": {"audio": {"depth": "16"}},
                    }
                ]
            ),
            id="video-audio-depth-string",
        ),
        param(
            _minimal_benchmark_config(
                phases=[
                    {
                        "name": "profiling",
                        "type": "concurrency",
                        "requests": 1,
                        "concurrency": 1,
                        "duration": "5M",
                    }
                ]
            ),
            id="duration-uppercase-unit",
        ),
        param(
            _minimal_benchmark_config(
                phases=[
                    {
                        "name": "profiling",
                        "type": "concurrency",
                        "duration": 600,
                        "concurrency": 200,
                        "adaptiveScale": True,
                        "adaptiveSustainDuration": 120,
                        "sla": {"request_latency": {"p95": {"le": 30000}}},
                    }
                ]
            ),
            id="compact-adaptive-sla",
        ),
        param(
            _minimal_benchmark_config(
                phases=[
                    {
                        "name": "profiling",
                        "type": "concurrency",
                        "duration": 600,
                        "concurrency": 200,
                        "adaptiveScale": {
                            "enabled": True,
                            "control": {
                                "variable": "concurrency",
                                "min": 20,
                                "max": 200,
                            },
                            "assessmentPeriod": 30,
                            "sustainDuration": 120,
                            "sla": {"request_latency": {"p95": {"le": 30000}}},
                        },
                    }
                ]
            ),
            id="nested-adaptive-scale",
        ),
        param(
            _minimal_benchmark_config(
                phases=[
                    {
                        "name": "profiling",
                        "type": "concurrency",
                        "duration": 600,
                        "concurrency": 200,
                        "adaptive_scale": {
                            "enabled": True,
                            "control": {
                                "variable": "concurrency",
                                "min": 20,
                                "max": 200,
                            },
                            "assessment_period": 30,
                            "sustain_duration": 120,
                            "sla": {"request_latency": {"p95": {"le": 30000}}},
                        },
                    }
                ]
            ),
            id="nested-adaptive-scale-snake-case",
        ),
        param(
            _minimal_benchmark_config(
                phases=[
                    {
                        "name": "profiling",
                        "type": "fixed_schedule",
                        "requests": 1,
                        "duration": 10,
                        "adaptive_scale": {"enabled": False},
                    }
                ]
            ),
            id="fixed-schedule-disabled-adaptive-scale-block",
        ),
    ],
)  # fmt: skip
def test_generated_schema_accepts_runtime_normalization_special_cases(
    config: dict[str, Any],
) -> None:
    schema = _generated_schema()
    config = copy.deepcopy(config)
    benchmark = config["benchmark"]
    for key in [key for key, value in benchmark.items() if value is None]:
        del benchmark[key]

    AIPerfConfig.model_validate(copy.deepcopy(config))

    _assert_schema_accepts(schema, config)


def test_generated_schema_accepts_nested_adaptive_scale_numeric_templates() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "concurrency",
                "duration": 600,
                "concurrency": 200,
                "adaptiveScale": {
                    "enabled": True,
                    "control": {
                        "variable": "concurrency",
                        "min": "${ADAPTIVE_MIN:1}",
                        "max": "{{ adaptive_max }}",
                    },
                    "assessmentPeriod": "${ADAPTIVE_WINDOW:30}",
                    "minCompletedRequests": "{{ min_completed }}",
                    "sustainDuration": "${ADAPTIVE_SUSTAIN:120}",
                    "strategy": {
                        "type": "ramp_until_fail",
                        "baseStep": "{{ base_step }}",
                        "maxStepMultiplier": "${MAX_STEP_MULTIPLIER:2}",
                        "stepPercent": "{{ step_percent }}",
                    },
                    "sla": {"request_latency": {"p95": {"le": 30000}}},
                },
            }
        ]
    )

    _assert_schema_accepts(schema, config)


def test_generated_schema_accepts_nested_adaptive_scale_string_enabled() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "concurrency",
                "duration": 600,
                "concurrency": 200,
                "adaptiveScale": {
                    "enabled": "false",
                    "sustainDuration": 120,
                    "sla": {"request_latency": {"p95": {"le": 30000}}},
                },
            }
        ]
    )

    AIPerfConfig.model_validate(copy.deepcopy(config))
    _assert_schema_accepts(schema, config)


def test_generated_schema_rejects_nested_adaptive_scale_alias_invalid_bounds() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "concurrency",
                "duration": 600,
                "concurrency": 200,
                "adaptiveScale": {
                    "enabled": True,
                    "minConcurrency": 0,
                    "maxConcurrency": 0,
                    "sustainDuration": 120,
                    "sla": {"request_latency": {"p95": {"le": 30000}}},
                },
            }
        ]
    )

    with pytest.raises(ValidationError):
        AIPerfConfig.model_validate(copy.deepcopy(config))
    assert _schema_error_messages(schema, config)


def test_generated_schema_rejects_nested_adaptive_scale_invalid_bounds() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "concurrency",
                "duration": 600,
                "concurrency": 200,
                "adaptiveScale": {
                    "enabled": True,
                    "control": {"variable": "concurrency", "min": 0, "max": 0},
                    "assessmentPeriod": 0,
                    "minCompletedRequests": 0,
                    "sustainDuration": 0,
                    "strategy": {
                        "type": "ramp_until_fail",
                        "baseStep": 0,
                        "maxStepMultiplier": 0,
                        "stepPercent": 0,
                    },
                    "sla": {"request_latency": {"p95": {"le": 30000}}},
                },
            }
        ]
    )

    messages = _schema_error_messages(schema, config)
    assert messages
    assert any("not valid under any of the given schemas" in msg for msg in messages)


def test_generated_schema_rejects_nested_adaptive_scale_unknown_keys() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "concurrency",
                "duration": 600,
                "concurrency": 200,
                "adaptive_scale": {
                    "enabled": True,
                    "typo": 1,
                    "control": {"variable": "concurrency", "min": 1, "max": 200},
                    "sustain_duration": 120,
                    "sla": {"request_latency": {"p95": {"le": 30000}}},
                },
            }
        ]
    )

    with pytest.raises(ValidationError, match="unsupported field"):
        AIPerfConfig.model_validate(copy.deepcopy(config))
    assert _schema_error_messages(schema, config)


def test_config_rejects_adaptive_search_with_adaptive_scale_phase() -> None:
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "profiling",
                "type": "concurrency",
                "duration": 600,
                "concurrency": 200,
                "adaptive_scale": {
                    "enabled": True,
                    "control": {"variable": "concurrency", "min": 20, "max": 200},
                    "sustain_duration": 120,
                    "sla": {"request_latency": {"p95": {"le": 30000}}},
                },
            }
        ],
    )
    config["sweep"] = {
        "type": "adaptive_search",
        "search_space": [
            {
                "path": "phases.profiling.concurrency",
                "lo": 1,
                "hi": 1000,
                "kind": "int",
            }
        ],
        "objectives": [
            {
                "metric": "output_token_throughput",
                "stat": "avg",
                "direction": "maximize",
            }
        ],
        "max_iterations": 6,
    }

    with pytest.raises(ValidationError, match="adaptive_search sweeps cannot"):
        AIPerfConfig.model_validate(config)


def test_generated_schema_rejects_fixed_schedule_adaptive_scale() -> None:
    schema = _generated_schema()
    config = _minimal_benchmark_config(
        phases=[
            {
                "name": "fixed",
                "type": "fixed_schedule",
                "requests": 1,
                "duration": 10,
                "adaptiveScale": True,
                "adaptiveSustainDuration": 5,
                "sla": {"request_latency": {"p95": {"le": 30000}}},
            }
        ]
    )

    with pytest.raises(ValidationError, match="fixed_schedule"):
        AIPerfConfig.model_validate(copy.deepcopy(config))
    assert _schema_error_messages(schema, config)


@pytest.mark.parametrize(
    ("env", "config"),
    [
        param(
            {"AIPERF_TEST_URL": "http://localhost:8000/v1/chat/completions"},
            _minimal_benchmark_config(endpoint={"urls": ["${AIPERF_TEST_URL}"]}),
            id="env-var-string-field",
        ),
        param(
            {},
            _minimal_benchmark_config(
                endpoint={"urls": ["${AIPERF_TEST_URL:http://localhost:8000/v1/chat/completions}"]}
            ),
            id="env-var-default-string-field",
        ),
        param(
            {"AIPERF_TEST_CONCURRENCY": "4"},
            _minimal_benchmark_config(
                phases=[
                    {
                        "name": "profiling",
                        "type": "concurrency",
                        "requests": 10,
                        "concurrency": "${AIPERF_TEST_CONCURRENCY}",
                    }
                ]
            ),
            id="env-var-numeric-field",
        ),
        param(
            {"AIPERF_TEST_ISL": "512"},
            _minimal_benchmark_config(
                datasets=[
                    {
                        "name": "main",
                        "type": "synthetic",
                        "entries": 1,
                        "prompts": {"isl": "${AIPERF_TEST_ISL}", "osl": 128},
                    }
                ]
            ),
            id="env-var-distribution-scalar-field",
        ),
        param(
            {},
            {
                **_minimal_benchmark_config(
                    phases=[
                        {
                            "name": "profiling",
                            "type": "concurrency",
                            "requests": "{{ targetConcurrency * 10 }}",
                            "concurrency": "{{ targetConcurrency }}",
                        }
                    ],
                ),
                "variables": {"targetConcurrency": 4},
            },
            id="jinja-numeric-fields",
        ),
        param(
            {},
            {
                **_minimal_benchmark_config(
                    endpoint={"urls": ["{{ targetUrl }}"]},
                ),
                "variables": {"targetUrl": "http://localhost:8000/v1/chat/completions"},
            },
            id="jinja-string-field",
        ),
    ],
)  # fmt: skip
def test_generated_schema_accepts_pre_render_env_vars_and_jinja_templates(
    monkeypatch: pytest.MonkeyPatch,
    env: dict[str, str],
    config: dict[str, Any],
) -> None:
    schema = _generated_schema()
    config = copy.deepcopy(config)
    for key, value in env.items():
        monkeypatch.setenv(key, value)

    yaml_content = yaml.safe_dump(config, sort_keys=False)

    load_config_from_string(yaml_content)

    _assert_schema_accepts(schema, config)
